name: Python package

on:
  push:
  workflow_dispatch:
    inputs:
      run_non_integration_tests:
        description: 'Run non-integration tests'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make env
          pip list
          . env/bin/activate; pip list; deactivate
      - name: Test with pytest
        run: |
          make run_non_integration_tests
          make run_integration_tests
